import React, { Component } from 'react';
import { connect }          from 'react-redux';
import { compose }          from 'redux';

import './Funds.scss';

class Funds extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedTab: 0,
    }
  }

  componentWillMount() {
    this.unlisten = this.props.history.listen((location, action) => {
      let search = location.search;
      if (search.indexOf('?tab=') === 0) {
        switch(search.slice(5)) {
          case 'deposits':
            this.setState({ selectedTab: 1});
            break;
          case 'withdrawals':
            this.setState({ selectedTab: 2});
            break;
          case 'transactions':
            this.setState({ selectedTab: 4});
            break;
          default: 
            this.setState({ selectedTab: 0});
        }
      } else 
        this.setState({ selectedTab: 0});
    })
  }

  componentWillUnmount() {
    this.unlisten();
  }

  renderContent() {
    if (this.state.selectedTab === 0)
      return(
        <div className="fund-content">
          <div className="balance-block">
            <div className="balance-item">
              <div className="grey-text">Estimated Balance</div>
              <div className="balance">
                <div className="price">0.000</div>
                <div className="usd">USD</div>
              </div>
              <div className="grey-text">≈ 0.0000000 BTC</div>
            </div>
            <div className="balance-item">
              <div className="grey-text">Available Balance</div>
              <div className="balance">
                <div className="price green">0.000</div>
                <div className="usd">USD</div>
              </div>
              <div className="grey-text">≈ 0.0000000 BTC</div>
            </div>
            <div className="balance-item">
              <div className="grey-text">In Orders</div>
              <div className="balance">
                <div className="price red">0.000</div>
                <div className="usd">USD</div>
              </div>
              <div className="grey-text">≈ 0.0000000 BTC</div>
            </div>
          </div>
          <div className="title">Balance</div>
          <div className="wallet-block">
            <div className="wb-header">
              <div className="check-option">
                <div className="check">
                  <div className="circle"></div>
                </div>
                <div className="co-text">Show zero balance wallets</div>
              </div>
              <div className="search-row">
                <i className="fa fa-search" aria-hidden="true"></i>
                <input className="sr-input" placeholder="Search in my balances..."/>
              </div>
            </div>
            <div className="text">No assets found</div>
          </div>
        </div>
      );
    if (this.state.selectedTab === 1)
      return(
        <div className="fund-content">
          <div className="deposit-block">
            <div className="db-header">
              <div className="db-title">Deposits</div>
              <img src={"https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg"} alt="" className="btc-img"></img>
              <div className="currency">
                BTC<i className="fa fa-angle-down" aria-hidden="true"></i>
              </div>
              <div className="av-text">Available BTC 0.000000000</div>
            </div>
            <div className="white-text">Deposit service is unavailable.</div>
            <div className="grey-text">
              Your 2 factor authentication method is disabled or outdated.<br/>
              Please enable 2 factor authentication in order to enable<br/>
              deposit service.
            </div>
            <div className="blue-button">Enable 2-Factor Authentications</div>
          </div>
          <div className="completed-block">
            <div className="cb-title">Completed Deposits | BTC</div>
            <div className="blue-text">No Transactions Available</div>
            <div className="white-text">You have no trasnactions yet.</div>
            <div className="white-text">Transactions are generated by buying/selling Executions, lending-related activities, and deposit/withdrawal actions.</div>
          </div>
        </div>
      );
    if (this.state.selectedTab === 2)
      return(
        <div className="fund-content">
          <div className="deposit-block">
            <div className="db-header">
              <div className="db-title">Withdrawals</div>
              <img src={"https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg"} alt="" className="btc-img"></img>
              <div className="currency">
                BTC<i className="fa fa-angle-down" aria-hidden="true"></i>
              </div>
              <div className="av-text">Available BTC <span className="green">0.000000000</span></div>
            </div>
            <div className="btc-image">
              <img src={"https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg"} alt=""></img>
            </div>
            <div className="currency-text">BTC</div>
            <div className="white-text">Withdrawal service is unavailable.</div>
            <div className="grey-text">
              Your 2 factor authentication method is disabled or outdated.<br/>
              Please enable 2 factor authentication in order to enable<br/>
              deposit service.
            </div>
            <div className="blue-button">Enable 2-Factor Authentications</div>
          </div>
          <div className="completed-block">
            <div className="cb-title">Withdrawal Requests | BTC</div>
            <div className="table-row">
              <div className="cell">ID</div>
              <div className="cell">Amount</div>
              <div className="cell">Fee</div>
              <div className="cell">Address</div>
              <div/>
              <div className="cell">Status</div>
              <div className="cell">Created On</div>
              <div className="cell">Cancel</div>
              <div/>
            </div>
            </div>
          <div className="completed-block">
            <div className="cb-title">Completed Withdrawals | BTC</div>
            <div className="blue-text">No Transactions Available</div>
            <div className="white-text">You have no trasnactions yet.</div>
            <div className="white-text">Transactions are generated by buying/selling Executions, lending-related activities, and deposit/withdrawal actions.</div>
          </div>
        </div>
      );
      if (this.state.selectedTab === 3) {
        return (
          <div className="fund-content">
            <div className="order-block">
              <div className="ob-title">Open Orders</div>
              <div className="blue-text">No Live Orders</div>
              <div className="white-text">You have no live orders.</div>
              <div className="white-text">Once placed, orders are displayed here. Live orders can be edited or cancelled.</div>
            </div>
          </div>
        )
      }
      if (this.state.selectedTab === 4) {
        return (
          <div className="fund-content">
            <div className="order-block">
              <div className="ob-title">Transactions</div>
              <div className="account-row">
                <div className="text">Select Account</div>
                <img src={"https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg"} alt=""></img>
                <div className="text">BTC</div>
                <i className="fa fa-angle-down" aria-hidden="true"></i>
              </div>
              <div className="blue-text">No Live Orders</div>
              <div className="white-text">You have no trasnactions yet.</div>
              <div className="white-text">Transactions are generated by buying/selling Executions, lending-related activities, and deposit/withdrawal actions.</div>
            </div>
            <div className="title" style={{marginLeft: '30px'}}>Overview Report</div>
            <div className="overview-block">
              <div className="ob-title">Select Range</div>
              <div className="filter-row">
                <div className="ftext">From</div>
                <div className="dfilters">
                  <div className="item">
                    2020 <i className="fa fa-angle-down" aria-hidden="true"></i>
                  </div>
                  <div className="item">
                    May <i className="fa fa-angle-down" aria-hidden="true"></i>
                  </div>
                  <div className="item">
                    20 <i className="fa fa-angle-down" aria-hidden="true"></i>
                  </div>
                </div>
              </div>
              <div className="filter-row second">
                <div className="ftext">To</div>
                <div className="dfilters">
                  <div className="item">
                    2020 <i className="fa fa-angle-down" aria-hidden="true"></i>
                  </div>
                  <div className="item">
                    May <i className="fa fa-angle-down" aria-hidden="true"></i>
                  </div>
                  <div className="item">
                    20 <i className="fa fa-angle-down" aria-hidden="true"></i>
                  </div>
                </div>
              </div>
              <div className="sub-title">Transacted Volume:</div>
              <div className="text">Accounts with zero transacted volume during selected period will not be displayed.</div>
              <div className="send-button">Send Report Via Email</div>
            </div>
          </div>
        )
      }
  }

  render() {
    return (
      <div className="Funds">
        <div className="f-tabs">
          <div className={this.state.selectedTab===0?"tab active":"tab"}
            onClick={() => {this.setState({selectedTab: 0})}}>Balance</div>
          <div className={this.state.selectedTab===1?"tab active":"tab"}
            onClick={() => {this.setState({selectedTab: 1})}}>Deposits</div>
          <div className={this.state.selectedTab===2?"tab active":"tab"}
            onClick={() => {this.setState({selectedTab: 2})}}>Withdrawals</div>
          <div className={this.state.selectedTab===3?"tab active":"tab"}
            onClick={() => {this.setState({selectedTab: 3})}}>Open Orders</div>
          <div className={this.state.selectedTab===4?"tab active":"tab"}
            onClick={() => {this.setState({selectedTab: 4})}}>Transactions</div>
        </div>
        {this.renderContent()}
      </div>
    )
  }
}

const mapStateToProps = (state) => ({
});

const mapDispatchToProps = {
};

export default compose(connect(mapStateToProps, mapDispatchToProps))(Funds);